### ISSUE TITLE
Question on the order of operators in heterogeneous hilbert spaces

### ISSUE THREAD

**Issue by VolodyaCO** [netket/netket#1106]
I am finally working with heterogeneous Hilbert spaces and I noticed the following strange behaviour (I'm using commit bb53989dc47c3d2fb20c46acf027cc6f3ba56145):

```zsh
>>> import netket as nk
>>> n_max = 5
>>> hi = nk.hilbert.Fock(n_max, N=1) * nk.hilbert.Qubit()
>>> a = nk.operator.boson.destroy(hi, 0)
>>> sp = nk.operator.spin.sigmap(hi, 1)
>>> a*sp
LocalOperator(dim=2, acting_on=[[0, 1]], constant=0, dtype=float64)
>>> sp*a
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/vladimirvargas/Documents/Projects/physics/netket/netket/operator/_local_operator.py", line 377, in __mul__
    return op.__imatmul__(other)
  File "/Users/vladimirvargas/Documents/Projects/physics/netket/netket/operator/_local_operator.py", line 425, in __imatmul__
    return self._concrete_imatmul_(other)
  File "/Users/vladimirvargas/Documents/Projects/physics/netket/netket/operator/_local_operator.py", line 449, in _concrete_imatmul_
    prod = LocalOperator(self.hilbert, tot_operators, tot_act, dtype=self.dtype)
  File "/Users/vladimirvargas/Documents/Projects/physics/netket/netket/operator/_local_operator.py", line 269, in __init__
    self._add_operator(op, act)
  File "/Users/vladimirvargas/Documents/Projects/physics/netket/netket/operator/_local_operator.py", line 530, in _add_operator
    self.hilbert, operator, acting_on
  File "/Users/vladimirvargas/Documents/Projects/physics/netket/netket/operator/_local_operator.py", line 187, in _reorder_kronecker_product
    mat_sorted = mat[n_unsorted, :][:, n_unsorted]
IndexError: index 12 is out of bounds for axis 0 with size 12
```

Is this an intended behaviour? Since sp and a act on different parts of the system, they commute, but it looks like there's some sort of problem with this.

**Comment by VolodyaCO** [comment]
I noticed that I was using an old version. I updated it to ab1fc406f7765e7191fc9ebbb01f766fa4c627a2, but the same behaviour is still present

**Comment by PhilipVinc** [comment]
'Tis clearly a bug in _reorder_kronecker. I'm pretty sure we are not testing it enough with heterogeneous hilbert spaces.

The first works because reorder kronecker does nothing, as the acting on is already in the correct order.

Should be a relatively simple fix if you want to do it. You just have to find where it's making a wrong assumption

**Comment by PhilipVinc** [comment]
It's now fixed in the new Localoperator branch

**Comment by VolodyaCO** [comment]
Oh ok that was quick thanks. I guess this one will be closed automatically when the PR is merged

**Comment by PhilipVinc** [comment]
closed by #1095
