### ISSUE TITLE
Issue with `take` call in `DenseSymmIrrep`

### ISSUE THREAD

**Issue by attila-i-szabo** [netket/netket#1171]
When using any model containing `DenseSymmIrrep` with complex kernels with newer JAX versions, I get a variation of the following error:
```
Traceback (most recent call last):
  File "/home/vol06/scarf1036/NQS/new.py", line 164, in <module>
    gs.run(out=ma_name, n_iter=niter)
  File "/home/vol06/scarf1036/.venv/netket/lib/python3.9/site-packages/netket/driver/abstract_variational_driver.py", line 252, in run
    for step in self.iter(n_iter, step_size):
  File "/home/vol06/scarf1036/.venv/netket/lib/python3.9/site-packages/netket/driver/abstract_variational_driver.py", line 168, in iter
    dp = self._forward_and_backward()
  File "/home/vol06/scarf1036/.venv/netket/lib/python3.9/site-packages/netket/driver/vmc.py", line 132, in _forward_and_backward
    self._loss_stats, self._loss_grad = self.state.expect_and_grad(self._ham)
  File "/home/vol06/scarf1036/.venv/netket/lib/python3.9/site-packages/netket/vqs/mc/mc_state/state.py", line 595, in expect_and_grad
    return expect_and_grad(
  File "/home/vol06/scarf1036/.venv/netket/lib/python3.9/site-packages/netket/vqs/base.py", line 381, in expect_and_grad
    return expect_and_grad(
  File "/home/vol06/scarf1036/.venv/netket/lib/python3.9/site-packages/netket/vqs/mc/mc_state/expect_grad_chunked.py", line 49, in expect_and_grad_nochunking
    return expect_and_grad(vstate, operator, use_covariance, *args, **kwargs)
  File "/home/vol06/scarf1036/.venv/netket/lib/python3.9/site-packages/netket/vqs/mc/mc_state/expect_grad.py", line 54, in expect_and_grad
    Ō, Ō_grad, new_model_state = grad_expect_hermitian(
  File "/home/vol06/scarf1036/.venv/netket/lib/python3.9/site-packages/netket/vqs/mc/mc_state/expect_grad.py", line 149, in grad_expect_hermitian
    _, vjp_fun, *new_model_state = nkjax.vjp(
  File "/home/vol06/scarf1036/.venv/netket/lib/python3.9/site-packages/netket/jax/_vjp.py", line 156, in vjp
    return vjp_cc(fun, *primals, has_aux=has_aux, conjugate=conjugate)
  File "/home/vol06/scarf1036/.venv/netket/lib/python3.9/site-packages/netket/jax/_vjp.py", line 41, in vjp_cc
    out, _vjp_fun = jax.vjp(fun, *primals, has_aux=False)
  File "/home/vol06/scarf1036/.venv/netket/lib/python3.9/site-packages/netket/vqs/mc/mc_state/expect_grad.py", line 150, in <lambda>
    lambda w: model_apply_fun({"params": w, **model_state}, σ, mutable=mutable),
  File "/home/vol06/scarf1036/.venv/netket/lib/python3.9/site-packages/netket/utils/jax.py", line 76, in maybe_scalar_fun
    res = apply_fun(pars, xb, *args, **kwargs)
  File "/home/vol06/scarf1036/.venv/netket/lib/python3.9/site-packages/netket/vqs/mc/mc_state/state.py", line 191, in <lambda>
    lambda model, pars, x, **kwargs: model.apply(pars, x, **kwargs),
  File "/home/vol06/scarf1036/.venv/netket/lib/python3.9/site-packages/netket/models/equivariant.py", line 535, in __call__
    x_flip = self.dense_symm(-1 * x)
  File "/home/vol06/scarf1036/.venv/netket/lib/python3.9/site-packages/netket/nn/symmetric_linear.py", line 120, in __call__
    kernel = jnp.take(kernel, jnp.asarray(self.symmetries), 2)
  File "/home/vol06/scarf1036/.venv/netket/lib/python3.9/site-packages/jax/_src/numpy/lax_numpy.py", line 3339, in take
    return _take(a, indices, None if axis is None else operator.index(axis), out,
  File "/home/vol06/scarf1036/.venv/netket/lib/python3.9/site-packages/jax/_src/numpy/lax_numpy.py", line 3397, in _take
    return lax.gather(a, indices[..., None], dimension_numbers=dnums,
jax._src.source_info_util.JaxStackTraceBeforeTransformation: TypeError: 'NoneType' object is not iterable
```
The error message flags up this `take` function call: 
https://github.com/netket/netket/blob/1ba051e332614b23cf4d876becdad92904d2d017/netket/nn/symmetric_linear.py#L117-L120
and indeed, replacing line 120 with
```python
kernel = kernel[:,:,jnp.asarray(self.symmetries)]
```
fixes the issue. I can submit this fix as a PR, but it would be good to figure out what's going on—the two bits of code are equivalent, so it's worrying that one fails. Here's what we know so far:
* The issue is there for JAX 0.3.4 but not for JAX 0.2.25
* It only affects `DenseSymmIrrep` because only that uses `take` (and probably `DenseSymmMatrix` but we don't use that for anything serious)
* It only affects complex kernels, not real ones
* It only affects the backward pass (the exception is raised from `vjp` _after_ local energies are computed)
* It only affects the GPU backend, but not the CPU one

The last one in particular suggests this is a JAX issue. I tried to produce a MNWE that doesn't use NetKet functionality but didn't succeed so far.

**Comment by PhilipVinc** [comment]
Jax people have been refactoring the code dealing with indexing recently and they might have broken something. 

If you open an issue on the jax repository explaining the issue with a Working example that triggers the bug using netket (not minimal), highlighting the line that you change (before/after) and the fact that this broke in recent jax versions, 

I'll try to reduce it to a MWE so it can be fixed.

**Comment by attila-i-szabo** [comment]
Okay, I've managed to make a much smaller example (still using netket), I'll open an issue over at Jax

**Comment by PhilipVinc** [comment]
It seems to me that thanks to @YouJiacheng this is fixed on jax master

**Comment by attila-i-szabo** [comment]
Indeed. Shall I PR my "fix" in the first comment just to make sure GCNNs don't break for the JAX versions before this fix is out?

**Comment by PhilipVinc** [comment]
Let me check if they are exactly equivalent in the generated code, as to avoid performance regressions...

(Else, we can always just do 
```python
# workaround Jax#10416 bug fixed in v0.3.18
if jax.__version__ < (0,3,18):
   kernel = kernel[:,:,jnp.asarray(self.symmetries)]
else:
  kernel = take...
```
)

**Comment by femtobit** [comment]
Can we also add a test that would have caught this problem? It seems we were lacking coverage of that part of the code.

**Comment by attila-i-szabo** [comment]
I'm pretty sure this one would die for `mode='irreps'`:
https://github.com/netket/netket/blob/30af4dfc6e060d80cc4199bc47948134c01532b3/test/models/test_gcnn.py#L64-L90
What JAX version(s) do we use to run the tests?

**Comment by PhilipVinc** [comment]
>What JAX version(s) do we use to run the tests?

We test the latest jax version and the oldest we support

**Comment by femtobit** [comment]
> EDIT No, this one would be fine because we only test dtype=float. Should we add @pytest.mark.parametrize("dtype", [float, complex]) to cover it?

In principle I think this would be great. The only question is whether this would add a lot of runtime... Some of the GCNN tests already take a lot of time, IIRC.

**Comment by PhilipVinc** [comment]
We should do the same thing that @wdphy16 did for Autoregressive network, which only tests a deterministic random subset of them on ci

**Comment by attila-i-szabo** [comment]
> > EDIT No, this one would be fine because we only test dtype=float. Should we add @pytest.mark.parametrize("dtype", [float, complex]) to cover it?
> 
> In principle I think this would be great. The only question is whether this would add a lot of runtime... Some of the GCNN tests already take a lot of time, IIRC.

The 4 `test_gcnn` runs we have now take ~70 seconds in total, we'd get about that much extra. I'm not sure how bad that is, nor how we could test this issue in cheaper way.

Speaking of slow tests, why is `test_gcnn_equivariance` so extremely slow? There are instances that take longer than the slowest `test_gcnn` (which has to set up VMC and run it!)

> We should do the same thing that @wdphy16 did for Autoregressive network, which only tests a deterministic random subset of them on ci

Could you elaborate? My worry is that this issue affects one or two runs out of the 8 we'd go up to, so a random susbet would easily miss it.

**Comment by femtobit** [comment]
I am not a huge fan of only running a random subset of the tests in CI. Especially if it is the same subset all the time, how do we even know the other tests actually work on, say, Python 3.7?

> Speaking of slow tests, why is test_gcnn_equivariance so extremely slow? There are instances that take longer than the slowest test_gcnn (which has to set up VMC and run it!)

Could it be compilation times? I feel nowadays compilation takes up a quite significant part of our test runtime and unfortunately there is not much we can do about that as, e.g., making the systems in the test cases smaller does not help with compilation (if anyone has an idea, I'd be curious to hear it).

**Comment by PhilipVinc** [comment]
>I am not a huge fan of only running a random subset of the tests in CI. Especially if it is the same subset all the time, how do we even know the other tests actually work on, say, Python 3.7?

I partly agree with you.

> Could it be compilation times? 

It might be. Or maybe it's computing some group-theory stuff which will only be done once.

**Comment by attila-i-szabo** [comment]
> > Could it be compilation times?
> 
> It might be. Or maybe it's computing some group-theory stuff which will only be done once.

Could be either, though I don't think it's the group-theory stuff (I've just tested on my laptop, the tests take ~30 sec, the group theory involved in <1 sec).

OTOH `test_gcnn_equivariance` evaluates a GCNN for every rotated etc. version of some random state **in a loop** I'm pretty sure we should combine them in one batch and call the GCNN only once

**Comment by PhilipVinc** [comment]
anything speeding up the tests would be welcome.
The two GCNN tests show up in the top 10 for time taken...

```python
92.76s call     test/operator/test_operator.py::test_produce_elements_in_hilbert[Bose Hubbard-get_conn]
[6199](https://github.com/netket/netket/runs/6232164427?check_suite_focus=true#step:8:6199)
42.78s call     test/variational/test_autoreg.py::test_vmc_same[conv2d_dilation-fock-complex128-2]
[6200](https://github.com/netket/netket/runs/6232164427?check_suite_focus=true#step:8:6200)
41.90s call     test/sampler/test_sampler.py::test_correct_sampling[MetropolisPT(Local): Fock-, mpow=1]
[6201](https://github.com/netket/netket/runs/6232164427?check_suite_focus=true#step:8:6201)
41.60s call     test/variational/test_autoreg.py::test_vmc_same[conv2d_dilation-spin_1-complex128-2]
[6202](https://github.com/netket/netket/runs/6232164427?check_suite_focus=true#step:8:6202)
40.04s call     test/variational/test_autoreg.py::test_vmc_same[conv2d_dilation-spin_1-complex128-1]
[6203](https://github.com/netket/netket/runs/6232164427?check_suite_focus=true#step:8:6203)
38.83s call     test/variational/test_autoreg.py::test_vmc_same[conv2d-spin_1-complex128-2]
[6204](https://github.com/netket/netket/runs/6232164427?check_suite_focus=true#step:8:6204)
37.00s call     test/variational/test_autoreg.py::test_vmc_same[conv2d-fock-complex128-2]
[6205](https://github.com/netket/netket/runs/6232164427?check_suite_focus=true#step:8:6205)
35.36s call     test/variational/test_autoreg.py::test_vmc_same[conv2d-spin_1/2-complex128-2]
[6206](https://github.com/netket/netket/runs/6232164427?check_suite_focus=true#step:8:6206)
34.45s call     test/variational/test_autoreg.py::test_vmc_same[conv2d-spin_1/2-complex128-1]
[6207](https://github.com/netket/netket/runs/6232164427?check_suite_focus=true#step:8:6207)
32.41s call     test/driver/test_steadystate.py::test_estimate
[6208](https://github.com/netket/netket/runs/6232164427?check_suite_focus=true#step:8:6208)
27.37s call     test/stats/test_stats.py::test_stats_mean_std
[6209](https://github.com/netket/netket/runs/6232164427?check_suite_focus=true#step:8:6209)
27.07s call     test/models/test_gcnn.py::test_gcnn_equivariance[fft-Square-autom-True]
[6210](https://github.com/netket/netket/runs/6232164427?check_suite_focus=true#step:8:6210)
24.72s call     test/models/test_gcnn.py::test_gcnn_equivariance[irreps-Square-autom-True]
[6211](https://github.com/netket/netket/runs/6232164427?check_suite_focus=true#step:8:6211)
24.17s call     test/variational/test_autoreg.py::test_vmc_same[conv1d_dilation-spin_1/2-complex128-2]
[6212](https://github.com/netket/netket/runs/6232164427?check_suite_focus=true#step:8:6212)
22.75s call     test/operator/test_operator.py::test_produce_elements_in_hilbert[Bose Hubbard Complex-get_conn]
[6213](https://github.com/netket/netket/runs/6232164427?check_suite_focus=true#step:8:6213)
22.69s call     test/variational/test_autoreg.py::test_vmc_same[conv1d_dilation-spin_1-complex128-2]
[6214](https://github.com/netket/netket/runs/6232164427?check_suite_focus=true#step:8:6214)
22.64s call     test/variational/test_autoreg.py::test_vmc_same[conv1d-spin_1-complex128-2]
[6215](https://github.com/netket/netket/runs/6232164427?check_suite_focus=true#step:8:6215)
22.06s call     test/dynamics/test_driver.py::test_one_step_lindbladian[Heun(dt=0.01)]
[6216](https://github.com/netket/netket/runs/6232164427?check_suite_focus=true#step:8:6216)
21.88s call     test/models/test_gcnn.py::test_gcnn[True-fft]
[6217](https://github.com/netket/netket/runs/6232164427?check_suite_focus=true#step:8:6217)
21.75s call     test/variational/test_autoreg.py::test_vmc_same[conv1d-spin_1/2-complex128-1]
[6218](https://github.com/netket/netket/runs/6232164427?check_suite_focus=true#step:8:6218)
18.26s call     test/stats/test_stats.py::test_tau_corr
[6219](https://github.com/netket/netket/runs/6232164427?check_suite_focus=true#step:8:6219)
17.20s call     test/variational/test_autoreg.py::test_vmc_same[conv2d_dilation-spin_1/2-float64-2]
[6220](https://github.com/netket/netket/runs/6232164427?check_suite_focus=true#step:8:6220)
16.61s call     test/variational/test_autoreg.py::test_vmc_same[conv2d-spin_1/2-float64-2]
[6221](https://github.com/netket/netket/runs/6232164427?check_suite_focus=true#step:8:6221)
16.38s call     test/models/test_gcnn.py::test_gcnn[False-fft]
[6222](https://github.com/netket/netket/runs/6232164427?check_suite_focus=true#step:8:6222)
```
