### ISSUE TITLE
Sharding errors in sampler when using `reset_chains` in multi-node setting

### ISSUE THREAD

**Issue by therooler** [netket/netket#1726]
Hey,

I'm on `jax==0.4.23` and `jaxlib==0.4.23+cuda11.cudnn86`, Netket commit a4a9af222eaaedf9a55e1b36f8666116f1a4cbc4. My test setup is 

- 2 nodes
- 3 GPUs per node (single process per node, each process sees 3 GPUs)

I've been using Netket to do some multi-GPU calculations with the native JAX parallelization backend. For a single process, single node with multiple-gpus things work great! I got 8 GPUs running in parallel without any issues. 

For the system sizes and number of samples I need, this is unfortunately not enough, so I have been trying to get a multi-node configuration working. Here I ran into an issue with the `reset_chains` option of the Monte Carlo sampler. 

This is my minimal working example:

```python
import os
import argparse
import jax
import subprocess

parser = argparse.ArgumentParser(description='Set parameters')
parser.add_argument('--dist-url')
parser.add_argument('--world_size')
parser.add_argument('--gpus_per_node')
parser.add_argument('--rank')
args = parser.parse_args()

print(
    f"{args.rank}:"
    f" {subprocess.run(['nvidia-smi', '--query-gpu=uuid', '--format=csv,noheader'], check=True, capture_output=True).stdout}"
)

jax.distributed.initialize(coordinator_address=args.dist_url,
                           num_processes=int(args.world_size),
                           process_id=int(args.rank),
                           local_device_ids=list(range(int(args.gpus_per_node)))
                           )
print('devices', jax.devices())
print('local devices', jax.local_devices())
os.environ["NETKET_EXPERIMENTAL_SHARDING"] = "1"
os.environ["XLA_PYTHON_CLIENT_PREALLOCATE"] = "false"

# from test_multinode_2_netket_main import main
import netket as nk

L = 5
Lx = L
Ly = L
L = Lx * Ly
nsamples = 2 ** 12

ntrain_steps = 100
hilbert = nk.hilbert.Spin(0.5, L)
model = nk.models.RBM(param_dtype=complex, alpha=1, use_hidden_bias=True)
sampler = nk.sampler.MetropolisLocal(hilbert, n_chains_per_rank_or_device=2 ** 9, reset_chains=False)
phi = nk.vqs.MCState(sampler=sampler, model=model, n_samples=int(nsamples / jax.device_count()))
optimizer = nk.optimizer.Adam(learning_rate=0.01)

ham_graph = nk.graph.Square(Lx)
energy_operator = nk.operator._ising.IsingJax(hilbert, ham_graph, h=1.0, J=1.0)
vmc_driver = nk.driver.VMC(energy_operator, optimizer, variational_state=phi)
vmc_driver.run(n_iter=ntrain_steps - vmc_driver._step_count, show_progress=True)
```
which prints: 
```stdout
0: b'GPU-8ff3f8f7-f62c-8c7e-4deb-de80c6e7c815\nGPU-d33799a1-440f-fcd6-bedd-01e97ea0be72\nGPU-bd569045-0bf5-a0f0-e0c8-588eb75f593b\n'
devices [cuda(id=0), cuda(id=1), cuda(id=2), cuda(id=3), cuda(id=4), cuda(id=5)]
local devices [cuda(id=0), cuda(id=1), cuda(id=2)]
No output specified (out=[apath|nk.logging.JsonLogger(...)]).Running the optimization but not saving the output.
1: b'GPU-9cbccddd-2abb-9e33-64e2-ae1115bc31d1\nGPU-9c31cbe7-7226-2929-73ff-843d7c395873\nGPU-505c7a61-89bf-0f2f-c610-294ece3bce45\n'
devices [cuda(id=0), cuda(id=1), cuda(id=2), cuda(id=3), cuda(id=4), cuda(id=5)]
local devices [cuda(id=3), cuda(id=4), cuda(id=5)]
No output specified (out=[apath|nk.logging.JsonLogger(...)]).Running the optimization but not saving the output.
  0%|          | 0/100 [00:00<?, ?it/s]
  0%|          | 0/100 [00:15<?, ?it/s, Energy=-24.76-0.00j ± 0.13 [σ²=48.58]]
  0%|          | 0/100 [00:11<?, ?it/s, Energy=-25.23-0.00j ± 0.13 [σ²=50.42]]
  1%|          | 1/100 [00:11<19:10, 11.63s/it, Energy=-25.23-0.00j ± 0.13 [σ²=50.42]]
  1%|          | 1/100 [00:22<19:10, 11.63s/it, Energy=-25.45+0.00j ± 0.13 [σ²=48.90]]
  2%|▏         | 2/100 [00:22<17:51, 10.94s/it, Energy=-25.45+0.00j ± 0.13 [σ²=48.90]]
```
Which is great. However, changing the reset option:
```python
...
sampler = nk.sampler.MetropolisLocal(hilbert, n_chains_per_rank_or_device=2 ** 9, reset_chains=True)
...
```
Gives me this error:
```python-traceback
jax.errors.SimplifiedTraceback: For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/fs01/home/roeland/dwave/experiments/vaughn/test_netket/test_multinode_2_netket.py", line 47, in <module>
    vmc_driver.run(n_iter=ntrain_steps - vmc_driver._step_count, show_progress=True)
  File "/h/roeland/condaenvs/netket/lib/python3.10/site-packages/netket/driver/abstract_variational_driver.py", line 294, in run
    for step in self.iter(n_iter, step_size):
  File "/h/roeland/condaenvs/netket/lib/python3.10/site-packages/netket/driver/abstract_variational_driver.py", line 204, in iter
    dp = self._forward_and_backward()
  File "/h/roeland/condaenvs/netket/lib/python3.10/site-packages/netket/driver/vmc.py", line 127, in _forward_and_backward
    self._loss_stats, self._loss_grad = self.state.expect_and_grad(self._ham)
  File "/h/roeland/condaenvs/netket/lib/python3.10/site-packages/netket/vqs/mc/mc_state/state.py", line 618, in expect_and_grad
    return expect_and_grad(
  File "/h/roeland/condaenvs/netket/lib/python3.10/site-packages/netket/utils/plum/function.py", line 366, in __call__
    return _convert(method(*args, **kw_args), return_type)
  File "/h/roeland/condaenvs/netket/lib/python3.10/site-packages/netket/vqs/mc/mc_state/expect_grad.py", line 58, in expect_and_grad_default_formula
    Ō, Ō_grad = expect_and_forces(vstate, Ô, chunk_size, *args, mutable=mutable)
  File "/h/roeland/condaenvs/netket/lib/python3.10/site-packages/netket/utils/plum/function.py", line 366, in __call__
    return _convert(method(*args, **kw_args), return_type)
  File "/h/roeland/condaenvs/netket/lib/python3.10/site-packages/netket/vqs/mc/mc_state/expect_forces.py", line 48, in expect_and_forces
    σ, args = get_local_kernel_arguments(vstate, Ô)
  File "/h/roeland/condaenvs/netket/lib/python3.10/site-packages/netket/utils/plum/function.py", line 366, in __call__
    return _convert(method(*args, **kw_args), return_type)
  File "/h/roeland/condaenvs/netket/lib/python3.10/site-packages/netket/vqs/mc/mc_state/expect.py", line 75, in get_local_kernel_arguments
    σ = vstate.samples
  File "/h/roeland/condaenvs/netket/lib/python3.10/site-packages/netket/vqs/mc/mc_state/state.py", line 520, in samples
    self.sample()
  File "/h/roeland/condaenvs/netket/lib/python3.10/site-packages/netket/vqs/mc/mc_state/state.py", line 487, in sample
    self.sampler_state = self.sampler.reset(
  File "/h/roeland/condaenvs/netket/lib/python3.10/site-packages/netket/sampler/base.py", line 262, in reset
    return sampler._reset(wrap_afun(machine), parameters, state)
  File "/h/roeland/condaenvs/netket/lib/python3.10/site-packages/netket/sampler/metropolis.py", line 413, in _reset
    σ = sampler.rule.random_state(sampler, machine, parameters, state, rng)
  File "/h/roeland/condaenvs/netket/lib/python3.10/site-packages/netket/sampler/rules/base.py", line 142, in random_state
    return sampler.hilbert.random_state(
  File "/h/roeland/condaenvs/netket/lib/python3.10/site-packages/netket/hilbert/abstract_hilbert.py", line 86, in random_state
    return random.random_state(self, key, size, dtype=dtype)
  File "/h/roeland/condaenvs/netket/lib/python3.10/site-packages/netket/utils/plum/function.py", line 366, in __call__
    return _convert(method(*args, **kw_args), return_type)
  File "/h/roeland/condaenvs/netket/lib/python3.10/site-packages/netket/hilbert/random/spin.py", line 34, in random_state
    return jnp.asarray(rs * two - (n_states - 1), dtype=dtype)
  File "/h/roeland/condaenvs/netket/lib/python3.10/site-packages/jax/_src/numpy/array_methods.py", line 271, in deferring_binary_op
    return binary_op(*args)
RuntimeError: Running operations on `Array`s that are not fully addressable by this process (i.e. `Array`s with data sharded across multiple devices and processes.) is dangerous. It’s very important that all processes run the same cross-process computations in the same order otherwise it can lead to hangs. If you’re not already familiar with JAX’s multi-process programming model, please read https://jax.readthedocs.io/en/latest/multi_process.html. To fix this error, run your `jitted` computation inside `with jax.spmd_mode('allow_all'):` context manager.
```
This problem does not occur for single process multi-gpu configuration. Do these arrays in `hilbert.random.spin.py`
```python
n_states = int(2 * S + 1)
rs = jax.random.randint(key, shape=shape, minval=0, maxval=n_states)

two = jnp.asarray(2, dtype=dtype)
```
maybe need to be distributed to all devices or something?

**Comment by PhilipVinc** [comment]
Can you try to add a @jax.jit to the MetropolisSampler.reset method?

Otherwise @inailuig might know better.

**Comment by PhilipVinc** [comment]
Solved by #1727 , released few moments ago in netket 3.11.1

**Comment by therooler** [comment]
Thanks guys, I appreciate the quick fix!
