### ISSUE TITLE
TDVP drivers not measuring loss at initial time - error in callbacks.InvalidLossStopping

### ISSUE THREAD

**Issue by lindamauron** [netket/netket#1895]
In the TDVP drivers, the loss is not measured at initial time. Due to this, callbacks such as `InvalidLossStopping` raise an error at the first step because the dictionary key does not exist:
```python
Traceback (most recent call last):
  File "/Users/lindamauron/Projects/CSQS/test.py", line 25, in <module>
    te.run(
  File "/Users/lindamauron/environments/lastupdate/lib/python3.11/site-packages/netket/experimental/driver/tdvp_common.py", line 378, in run
    if not callback(step, log_data, self):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lindamauron/environments/lastupdate/lib/python3.11/site-packages/netket/callbacks/invalidlossstopping.py", line 65, in __call__
    loss = np.real(getattr(log_data[driver._loss_name], self.monitor))
                           ~~~~~~~~^^^^^^^^^^^^^^^^^^^
KeyError: 'Generator'
```
Yet, using a VMC driver, no such error is raised, since the energy is measured and saved from the beginning. 

Minimal working example :
```python
import netket as nk
import netket.experimental as nkx

hi = nk.hilbert.Spin(1/2)

ma = nk.models.Jastrow()
sa = nk.sampler.MetropolisLocal(hi, n_chains=10)
vs = nk.vqs.MCState(sa,ma,n_samples=100, n_discard_per_chain=10)

############################ All operators for measuring ############################

H = -nk.operator.spin.sigmax(hi,0)

te = nkx.TDVP(
    H,
    variational_state=vs,
    integrator=nkx.dynamics.RK4(dt=1e-2),
    t0=0.,
    qgt=nk.optimizer.qgt.QGTJacobianPyTree(diag_shift=0, holomorphic=True),
    error_norm="qgt",
    linear_solver=nk.optimizer.solver.svd(rcond=1e-8)
)

te.run(
    T=0.05,
    callback=nk.callbacks.InvalidLossStopping(patience=2),
)
```

Without the callback, the output of this code yields 
```python
data = {
        "t":{"iters":[0.0,0.01,0.02,0.03,0.04,0.05],"value":[0.0,0.01,0.02,0.03,0.04,0.05]},
        "acceptance":{"iters":[0.01,0.02,0.03,0.04,0.05],"value":[1.0,1.0,1.0,1.0,1.0]},
        "Generator":{"iters":[0.01,0.02,0.03,0.04,0.05],"Mean":{"real":[-1.0,-1.0,-1.0,-1.0,-1.0],"imag":[0.0,0.0,0.0,0.0,0.0]},"Variance":[0.0,0.0,0.0,0.0,0.0],"Sigma":[null,null,null,null,null],"R_hat":[null,null,null,null,null],"TauCorr":[null,null,null,null,null]}
}
```

**Comment by PhilipVinc** [comment]
It happens because loss_stats is not present (see Tdvp common line 367, which is supposed to populate the dictionary)

The responsibility to fill this key should be of the function _iter which is supposed to go from time t to t+dt (where dt is the step between two times at which the callbacks and logging is called).

the logic is convoluted because of the need to print the progress bar…

care to make a PR?
