### ISSUE TITLE
pip installation of netket successful, but loading fails

### ISSUE THREAD

**Issue by frolandh** [netket/netket#1929]
I have a mac M3 chip running Sonoma. I installed netket using pip, but trying to import netket fails. The following is the output of python -m netket.tools.info

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 188, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/Users/HenryFroland/Library/Python/3.9/lib/python/site-packages/netket/__init__.py", line 17, in <module>
    from .utils import config
  File "/Users/HenryFroland/Library/Python/3.9/lib/python/site-packages/netket/utils/__init__.py", line 15, in <module>
    from .config_flags import config
  File "/Users/HenryFroland/Library/Python/3.9/lib/python/site-packages/netket/utils/config_flags.py", line 296, in <module>
    config.define(
  File "/Users/HenryFroland/Library/Python/3.9/lib/python/site-packages/netket/utils/config_flags.py", line 108, in define
    callback(self._values[name])
  File "/Users/HenryFroland/Library/Python/3.9/lib/python/site-packages/netket/utils/config_flags.py", line 289, in _update_x64
    from jax import config as jax_config
  File "/Users/HenryFroland/Library/Python/3.9/lib/python/site-packages/jax/__init__.py", line 25, in <module>
    from jax._src.cloud_tpu_init import cloud_tpu_init as _cloud_tpu_init
  File "/Users/HenryFroland/Library/Python/3.9/lib/python/site-packages/jax/_src/cloud_tpu_init.py", line 17, in <module>
    from jax._src import config
  File "/Users/HenryFroland/Library/Python/3.9/lib/python/site-packages/jax/_src/config.py", line 27, in <module>
    from jax._src import lib
  File "/Users/HenryFroland/Library/Python/3.9/lib/python/site-packages/jax/_src/lib/__init__.py", line 84, in <module>
    cpu_feature_guard.check_cpu_features()
RuntimeError: This version of jaxlib was built using AVX instructions, which your CPU and/or operating system do not support. This error is frequently encountered on macOS when running an x86 Python installation on ARM hardware. In this case, try installing an ARM build of Python. Otherwise, you may be able work around this issue by building jaxlib from source.

**Comment by gcarleo** [comment]
looks like you are maybe not using a native version of python for arm processors ?

**Comment by PhilipVinc** [comment]
- you are using python 3.9 which is no longer supported by recent versions of jax and netket
- You are running under rosetta, which does not support AVX. Jax requires AVX. You should not run under rosetta.

By new suggestion would be to [install uv](https://docs.astral.sh/uv/getting-started/installation/) and use it for everything. It's a much better tool than anything else.

```
curl -LsSf https://astral.sh/uv/install.sh | sh

# go to some folder
mkdir myproject
uv python install 3.12
uv init --no-project
uv run python
# or
uv run python your script.py
```

**Comment by frolandh** [comment]
It seems like this works, thanks! To be clear (I haven't used uv before), anytime I would like to run a script using netket I just need to call uv run python myscript.py?

**Comment by PhilipVinc** [comment]
Yes.
If you are running a script you can also just run `uv run myscript.py`, though that is equivalent to `uv run python myscript.py`.

If you want to add other dependencies just do `uv add package` or `uv remove package`. He will add them to the pyproject.toml file.

The advantage is that uv will automatically manage a hidden python environment for you and ensure that you always have the right dependencies installed, as specified in the pyproject.toml file
