### ISSUE TITLE
`build_docs.py` fails when generating docs for PR #218

### ISSUE THREAD

**Issue by femtobit** [netket/netket#222]
The `build_docs.py` script currently fails for #218.
```
$ python3 build_docs.py 
Docs for  <class 'netket._C_netket.graph.CustomGraph'>
Docs for  <class 'netket._C_netket.graph.Graph'>
Docs for  <class 'netket._C_netket.graph.Hypercube'>
Docs for  <class 'netket._C_netket.graph.Lattice'>
Docs for  <class 'netket._C_netket.sampler.CustomSampler'>
Docs for  <class 'netket._C_netket.sampler.CustomSamplerPt'>
Docs for  <class 'netket._C_netket.sampler.ExactSampler'>
Docs for  <class 'netket._C_netket.sampler.MetropolisExchange'>
Docs for  <class 'netket._C_netket.sampler.MetropolisExchangePt'>
Docs for  <class 'netket._C_netket.sampler.MetropolisHamiltonian'>
Docs for  <class 'netket._C_netket.sampler.MetropolisHamiltonianPt'>
Docs for  <class 'netket._C_netket.sampler.MetropolisHop'>
Docs for  <class 'netket._C_netket.sampler.MetropolisLocal'>
Docs for  <class 'netket._C_netket.sampler.MetropolisLocalPt'>
Docs for  <class 'netket._C_netket.sampler.Sampler'>
Docs for  <class 'netket._C_netket.hilbert.Boson'>
Docs for  <class 'netket._C_netket.hilbert.CustomHilbert'>
Docs for  <class 'netket._C_netket.hilbert.Hilbert'>
Docs for  <class 'netket._C_netket.hilbert.Spin'>
Docs for  <class 'netket._C_netket.operator.AbstractMatrixWrapper'>
Docs for  <class 'netket._C_netket.operator.BoseHubbard'>
Docs for  <class 'netket._C_netket.operator.DenseMatrixWrapper'>
Docs for  <class 'netket._C_netket.operator.DirectMatrixWrapper'>
Docs for  <class 'netket._C_netket.operator.GraphOperator'>
Docs for  <class 'netket._C_netket.operator.LocalOperator'>
Docs for  <class 'netket._C_netket.operator.SparseMatrixWrapper'>
Docs for  <class 'netket._C_netket.variational.Vmc'>
Traceback (most recent call last):
  File "build_docs.py", line 52, in <module>
    build_docs(submodules=submodules)
  File "build_docs.py", line 41, in build_docs
    markdown = format.format_class(clsm[1])
  File "<...>/netket/Docs/format.py", line 55, in format_class
    match = clex.extract(method[0])
  File "<...>/netket/Docs/extract.py", line 132, in extract
    return types[self.dtype]()
  File "<...>/netket/Docs/extract.py", line 360, in extract_function
    return self.findall(pattern, ids)
  File "<...>/netket/Docs/extract.py", line 199, in findall
    r'Unable to extract docstring for `%s`' % self.query)
NameError: Unable to extract docstring for `iter`
```

This is probably caused in some way by the `Vmc.iter`  function being dynamically added to VMC in Python:
https://github.com/netket/netket/blob/12b8e68abf931c9ef44d078ac9bbd924b769c293/netket/variational.py#L6-L26

@ooreilly Do you have an idea what exactly causes the issue here and how to fix it?

**Comment by ooreilly** [comment]
@femtobit My guess is that the problem is due to the docstring being a standard python docstring but `build_docs.py` is trying to treat it as a pybind docstring. I am working on a fix.

**Comment by femtobit** [comment]
@ooreilly Ah, yes, that could be the problem. Thanks for looking into it.

**Comment by ooreilly** [comment]
@femtobit Would it be ok to use the pybind docstring format instead? Otherwise this fix is going to take some more work I'm afraid.

Here's how to modify `variational.py`:
```python
   def _Vmc_iter(self, n_iter=None, step_size=1):
    """iter(self: Vmc, n_iter: int=None, step_size: int=1) -> int

        Returns a generator which advances the VMC optimization, yielding
        after every step_size steps up to n_iter.


        Args:
            n_iter (int=None): The number of steps or None, for no limit.
            step_size (int=1): The number of steps the simulation is advanced.

        Yields:
            int: The current step.
    """
```
Note that you have to put `iter` in the docstring since `variational.py` contains the line
```
Vmc.iter = _Vmc_iter
```
at the end.

**Comment by femtobit** [comment]
Good idea. I did this in [9545523](https://github.com/netket/netket/commit/9545523dd21c10a09b2bd8714835489f792783f0#diff-4008246625d1c953a7ef1b019835359b) and building the docs works now.

**Comment by ooreilly** [comment]
Great! Glad to see that it works. Let me know if you need support for non-pybind docstrings.

**Comment by femtobit** [comment]
> Great! Glad to see that it works. Let me know if you need support for non-pybind docstrings.

I think requiring the pybind11 format is fine for now. It's also a good think to have the docstrings consistent; whether a function or class is written in C++ or Python is after all an implementation detail.
