### ISSUE TITLE
[BUG] scalar + local_operator bug 

### ISSUE THREAD

**Issue by PhilipVinc** [netket/netket#444]
```
>>> 0+nk.operator.boson.number(hi,1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/filippovicentini/Documents/pythonenvs/1_Carleo_FFNN/lib/python3.7/site-packages/netket/operator/local_operator.py", line 245, in __radd__
    return self.__radd__(other)
  File "/Users/filippovicentini/Documents/pythonenvs/1_Carleo_FFNN/lib/python3.7/site-packages/netket/operator/local_operator.py", line 245, in __radd__
    return self.__radd__(other)
  File "/Users/filippovicentini/Documents/pythonenvs/1_Carleo_FFNN/lib/python3.7/site-packages/netket/operator/local_operator.py", line 245, in __radd__
    return self.__radd__(other)
  [Previous line repeated 996 more times]
RecursionError: maximum recursion depth exceeded
```

**Comment by PhilipVinc** [comment]
Only in radd.
ladd works

**Comment by gcarleo** [comment]
Was this solved?

**Comment by PhilipVinc** [comment]
don't think so.
For this we need to fix `LocalOperator.__radd__`

**Comment by gcarleo** [comment]
Looks like this was already known :) #539
