### ISSUE TITLE
Seed error

### ISSUE THREAD

**Issue by jwnys** [netket/netket#473]
Using:
```bash
numba 0.51.2
numpy 1.19.1
mpi4py 3.0.3
```
I obtain an error when importing netket (v3.0).
The error arises due to the seed(None) on line 90 in random.py.
Here's a backtrace:

```python
/usr/local/anaconda3/envs/netket_env/lib/python3.8/site-packages/netket/random.py:10: NumbaWarning: 
Compilation is falling back to object mode WITH looplifting enabled because Function seed failed at nopython mode lowering due to: cannot pickle 'mpi4py.MPI.Intracomm' object

File "../../../../../../usr/local/anaconda3/envs/netket_env/lib/python3.8/site-packages/netket/random.py", line 19:
def seed(seed=None):
    <source elided>
    """
    with objmode(derived_seed="int64"):
    ^

During: lowering "$59 = call $58(seed, func=$58, args=[Var(seed, random.py:19)], kws=(), vararg=None)" at /usr/local/anaconda3/envs/netket_env/lib/python3.8/site-packages/netket/random.py (19)
  @jit

---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
/usr/local/anaconda3/envs/netket_env/lib/python3.8/site-packages/numba/core/errors.py in new_error_context(fmt_, *args, **kwargs)
    744     try:
--> 745         yield
    746     except NumbaError as e:

/usr/local/anaconda3/envs/netket_env/lib/python3.8/site-packages/numba/core/lowering.py in lower_block(self, block)
    229                                    loc=self.loc, errcls_=defaulterrcls):
--> 230                 self.lower_inst(inst)
    231         self.post_block(block)

/usr/local/anaconda3/envs/netket_env/lib/python3.8/site-packages/numba/core/pylowering.py in lower_inst(self, inst)
    167         else:
--> 168             raise NotImplementedError(type(inst), inst)
    169 

NotImplementedError: (<class 'numba.core.ir.EnterWith'>, <numba.core.ir.EnterWith object at 0x7f8655d40c40>)

During handling of the above exception, another exception occurred:

LoweringError                             Traceback (most recent call last)
<ipython-input-1-027b8d5cab67> in <module>
     13 if PATH not in sys.path:
     14     sys.path.append(PATH)
---> 15 import netket as nk
     16 
     17 PATH = "../"

/usr/local/anaconda3/envs/netket_env/lib/python3.8/site-packages/netket/__init__.py in <module>
     29 ]
     30 
---> 31 from . import (
     32     dynamics,
     33     exact,

/usr/local/anaconda3/envs/netket_env/lib/python3.8/site-packages/netket/hilbert/__init__.py in <module>
      1 from .abstract_hilbert import AbstractHilbert, max_states
----> 2 from .custom_hilbert import CustomHilbert
      3 from .doubled_hilbert import DoubledHilbert
      4 from .spin import Spin
      5 from .boson import Boson

/usr/local/anaconda3/envs/netket_env/lib/python3.8/site-packages/netket/hilbert/custom_hilbert.py in <module>
      4 from numba import jit
      5 import numpy as _np
----> 6 from netket import random as _random
      7 
      8 

/usr/local/anaconda3/envs/netket_env/lib/python3.8/site-packages/netket/random.py in <module>
     88 # By default, the generator is initialized with a random seed (on node 0)
     89 # and then propagated correctly to the other nodes
---> 90 seed(None)

/usr/local/anaconda3/envs/netket_env/lib/python3.8/site-packages/numba/core/dispatcher.py in _compile_for_args(self, *args, **kws)
    432                     e.patch_message('\n'.join((str(e).rstrip(), help_msg)))
    433             # ignore the FULL_TRACEBACKS config, this needs reporting!
--> 434             raise e
    435 
    436     def inspect_llvm(self, signature=None):

/usr/local/anaconda3/envs/netket_env/lib/python3.8/site-packages/numba/core/dispatcher.py in _compile_for_args(self, *args, **kws)
    365                 argtypes.append(self.typeof_pyval(a))
    366         try:
--> 367             return self.compile(tuple(argtypes))
    368         except errors.ForceLiteralArg as e:
    369             # Received request for compiler re-entry with the list of arguments

/usr/local/anaconda3/envs/netket_env/lib/python3.8/site-packages/numba/core/compiler_lock.py in _acquire_compile_lock(*args, **kwargs)
     30         def _acquire_compile_lock(*args, **kwargs):
     31             with self:
---> 32                 return func(*args, **kwargs)
     33         return _acquire_compile_lock
     34 

/usr/local/anaconda3/envs/netket_env/lib/python3.8/site-packages/numba/core/dispatcher.py in compile(self, sig)
    817             self._cache_misses[sig] += 1
    818             try:
--> 819                 cres = self._compiler.compile(args, return_type)
    820             except errors.ForceLiteralArg as e:
    821                 def folded(args, kws):

/usr/local/anaconda3/envs/netket_env/lib/python3.8/site-packages/numba/core/dispatcher.py in compile(self, args, return_type)
     76 
     77     def compile(self, args, return_type):
---> 78         status, retval = self._compile_cached(args, return_type)
     79         if status:
     80             return retval

/usr/local/anaconda3/envs/netket_env/lib/python3.8/site-packages/numba/core/dispatcher.py in _compile_cached(self, args, return_type)
     90 
     91         try:
---> 92             retval = self._compile_core(args, return_type)
     93         except errors.TypingError as e:
     94             self._failed_cache[key] = e

/usr/local/anaconda3/envs/netket_env/lib/python3.8/site-packages/numba/core/dispatcher.py in _compile_core(self, args, return_type)
    103 
    104         impl = self._get_implementation(args, {})
--> 105         cres = compiler.compile_extra(self.targetdescr.typing_context,
    106                                       self.targetdescr.target_context,
    107                                       impl,

/usr/local/anaconda3/envs/netket_env/lib/python3.8/site-packages/numba/core/compiler.py in compile_extra(typingctx, targetctx, func, args, return_type, flags, locals, library, pipeline_class)
    625     pipeline = pipeline_class(typingctx, targetctx, library,
    626                               args, return_type, flags, locals)
--> 627     return pipeline.compile_extra(func)
    628 
    629 

/usr/local/anaconda3/envs/netket_env/lib/python3.8/site-packages/numba/core/compiler.py in compile_extra(self, func)
    361         self.state.lifted = ()
    362         self.state.lifted_from = None
--> 363         return self._compile_bytecode()
    364 
    365     def compile_ir(self, func_ir, lifted=(), lifted_from=None):

/usr/local/anaconda3/envs/netket_env/lib/python3.8/site-packages/numba/core/compiler.py in _compile_bytecode(self)
    423         """
    424         assert self.state.func_ir is None
--> 425         return self._compile_core()
    426 
    427     def _compile_ir(self):

/usr/local/anaconda3/envs/netket_env/lib/python3.8/site-packages/numba/core/compiler.py in _compile_core(self)
    403                 self.state.status.fail_reason = e
    404                 if is_final_pipeline:
--> 405                     raise e
    406         else:
    407             raise CompilerError("All available pipelines exhausted")

/usr/local/anaconda3/envs/netket_env/lib/python3.8/site-packages/numba/core/compiler.py in _compile_core(self)
    394             res = None
    395             try:
--> 396                 pm.run(self.state)
    397                 if self.state.cr is not None:
    398                     break

/usr/local/anaconda3/envs/netket_env/lib/python3.8/site-packages/numba/core/compiler_machinery.py in run(self, state)
    339                     (self.pipeline_name, pass_desc)
    340                 patched_exception = self._patch_error(msg, e)
--> 341                 raise patched_exception
    342 
    343     def dependency_analysis(self):

/usr/local/anaconda3/envs/netket_env/lib/python3.8/site-packages/numba/core/compiler_machinery.py in run(self, state)
    330                 pass_inst = _pass_registry.get(pss).pass_inst
    331                 if isinstance(pass_inst, CompilerPass):
--> 332                     self._runPass(idx, pass_inst, state)
    333                 else:
    334                     raise BaseException("Legacy pass in use")

/usr/local/anaconda3/envs/netket_env/lib/python3.8/site-packages/numba/core/compiler_lock.py in _acquire_compile_lock(*args, **kwargs)
     30         def _acquire_compile_lock(*args, **kwargs):
     31             with self:
---> 32                 return func(*args, **kwargs)
     33         return _acquire_compile_lock
     34 

/usr/local/anaconda3/envs/netket_env/lib/python3.8/site-packages/numba/core/compiler_machinery.py in _runPass(self, index, pss, internal_state)
    289             mutated |= check(pss.run_initialization, internal_state)
    290         with SimpleTimer() as pass_time:
--> 291             mutated |= check(pss.run_pass, internal_state)
    292         with SimpleTimer() as finalize_time:
    293             mutated |= check(pss.run_finalizer, internal_state)

/usr/local/anaconda3/envs/netket_env/lib/python3.8/site-packages/numba/core/compiler_machinery.py in check(func, compiler_state)
    262 
    263         def check(func, compiler_state):
--> 264             mangled = func(compiler_state)
    265             if mangled not in (True, False):
    266                 msg = ("CompilerPass implementations should return True/False. "

/usr/local/anaconda3/envs/netket_env/lib/python3.8/site-packages/numba/core/object_mode_passes.py in run_pass(self, state)
    143                                                state.flags)
    144 
--> 145         lowered = backend_object_mode()
    146         signature = typing.signature(state.return_type, *state.args)
    147         from numba.core.compiler import compile_result

/usr/local/anaconda3/envs/netket_env/lib/python3.8/site-packages/numba/core/object_mode_passes.py in backend_object_mode()
    138                                   (state.nargs - len(state.args)))
    139 
--> 140                 return self._py_lowering_stage(state.targetctx,
    141                                                state.library,
    142                                                state.func_ir,

/usr/local/anaconda3/envs/netket_env/lib/python3.8/site-packages/numba/core/object_mode_passes.py in _py_lowering_stage(self, targetctx, library, interp, flags)
     98         with targetctx.push_code_library(library):
     99             lower = pylowering.PyLower(targetctx, library, fndesc, interp)
--> 100             lower.lower()
    101             if not flags.no_cpython_wrapper:
    102                 lower.create_cpython_wrapper()

/usr/local/anaconda3/envs/netket_env/lib/python3.8/site-packages/numba/core/lowering.py in lower(self)
    134         if self.generator_info is None:
    135             self.genlower = None
--> 136             self.lower_normal_function(self.fndesc)
    137         else:
    138             self.genlower = self.GeneratorLower(self)

/usr/local/anaconda3/envs/netket_env/lib/python3.8/site-packages/numba/core/lowering.py in lower_normal_function(self, fndesc)
    188         # Init argument values
    189         self.extract_function_arguments()
--> 190         entry_block_tail = self.lower_function_body()
    191 
    192         # Close tail of entry block

/usr/local/anaconda3/envs/netket_env/lib/python3.8/site-packages/numba/core/lowering.py in lower_function_body(self)
    214             bb = self.blkmap[offset]
    215             self.builder.position_at_end(bb)
--> 216             self.lower_block(block)
    217         self.post_lower()
    218         return entry_block_tail

/usr/local/anaconda3/envs/netket_env/lib/python3.8/site-packages/numba/core/lowering.py in lower_block(self, block)
    228             with new_error_context('lowering "{inst}" at {loc}', inst=inst,
    229                                    loc=self.loc, errcls_=defaulterrcls):
--> 230                 self.lower_inst(inst)
    231         self.post_block(block)
    232 

/usr/local/anaconda3/envs/netket_env/lib/python3.8/contextlib.py in __exit__(self, type, value, traceback)
    129                 value = type()
    130             try:
--> 131                 self.gen.throw(type, value, traceback)
    132             except StopIteration as exc:
    133                 # Suppress StopIteration *unless* it's the same exception that

/usr/local/anaconda3/envs/netket_env/lib/python3.8/site-packages/numba/core/errors.py in new_error_context(fmt_, *args, **kwargs)
    750         newerr = errcls(e).add_context(_format_msg(fmt_, args, kwargs))
    751         tb = sys.exc_info()[2] if numba.core.config.FULL_TRACEBACKS else None
--> 752         reraise(type(newerr), newerr, tb)
    753 
    754 

/usr/local/anaconda3/envs/netket_env/lib/python3.8/site-packages/numba/core/utils.py in reraise(tp, value, tb)
     79     if value.__traceback__ is not tb:
     80         raise value.with_traceback(tb)
---> 81     raise value
     82 
     83 

LoweringError: Failed in object mode pipeline (step: object mode backend)
(<class 'numba.core.ir.EnterWith'>, <numba.core.ir.EnterWith object at 0x7f8655d40c40>)

File "../../../../../../usr/local/anaconda3/envs/netket_env/lib/python3.8/site-packages/netket/random.py", line 19:
def seed(seed=None):
    <source elided>
    """
    with objmode(derived_seed="int64"):
    ^

During: lowering "enter_with $phi10.0" at /usr/local/anaconda3/envs/netket_env/lib/python3.8/site-packages/netket/random.py (19)
```

**Comment by PhilipVinc** [comment]
I believe #471 should fix that.
Try to install that branch with `pip install git+https://github.com/netket/netket@fix_numba_issue

**Comment by gcarleo** [comment]
yes I just merged it, you can just pull from v3.0

**Comment by gcarleo** [comment]
it was some weird bug (or feature? who knows...) in the last version of numba...

**Comment by jwnys** [comment]
works like a charm! Thanks!
