### ISSUE TITLE
Error with GCNN

### ISSUE THREAD

**Issue by gcarleo** [netket/netket#701]
Hi, 

I was trying to reproduce the (very nice!) tutorial on GCNNs locally, with the following

```python
import netket as nk
import numpy as np
import jax

# Basis Vectors that define the positioning of the unit cell
basis_vectors = [[0, 1], [np.sqrt(3) / 2, -1 / 2]]

# Locations of atoms within the unit cell
atom_positions = [[0, 0], [np.sqrt(3) / 6, 1 / 2]]

# Number of unit cells in each direction
dimensions = [3, 3]

# Define the graph
graph = nk.graph.Lattice(
    basis_vectors=basis_vectors, atoms_coord=atom_positions, extent=dimensions
)

# Lattice translation operations
symmetries = graph.automorphisms()

# Hilbert space of spins on the graph
hi = nk.hilbert.Spin(s=1 / 2, N=graph.n_nodes, total_sz=0)

ha = nk.operator.Heisenberg(hilbert=hi, graph=graph)

# Feature dimensions of hidden layers, from first to last
feature_dims = (8, 8, 8, 8)

# Number of layers
num_layers = 4

# Define the GCNN
ma = nk.models.GCNN(symmetries=symmetries, layers=num_layers, features=feature_dims)

# Metropolis Local Sampling
sa = nk.sampler.MetropolisExchange(hi, graph=graph, n_chains=16)

# Optimizer
op = nk.optim.Sgd(learning_rate=0.01)
sr = nk.optim.SR(0.1)

# Variational monte carlo driver
gs = nk.VMC(ha, op, sa, ma, n_samples=1000, n_discard=100, sr=sr)

# Run the optimization for 300 iterations
gs.run(n_iter=300, out="test")
```

 but with the latest master version I get the following error

```
Traceback (most recent call last):
  File "/Users/giuscarl/Works/NetKet/netket/Examples/Heisenberg1d/heis_gconv.py", line 58, in <module>
    gs = nk.VMC(ha, op, sa, ma, n_samples=1000, n_discard=100, sr=sr)
  File "/Users/giuscarl/Works/NetKet/netket/netket/driver/vmc.py", line 70, in __init__
    variational_state = MCState(*args, **kwargs)
  File "/Users/giuscarl/Works/NetKet/netket/netket/variational/mc_state.py", line 192, in __init__
    self.init(seed, dtype=sampler.dtype)
  File "/Users/giuscarl/Works/NetKet/netket/netket/variational/mc_state.py", line 221, in init
    variables = self._init_fun({"params": key}, dummy_input)
  File "/Users/giuscarl/Works/NetKet/netket/netket/variational/mc_state.py", line 160, in <lambda>
    lambda model, *args, **kwargs: model.init(*args, **kwargs), model
  File "/Users/giuscarl/miniconda3/envs/netket_env/lib/python3.9/site-packages/flax/linen/module.py", line 884, in init
    _, v_out = self.init_with_output(rngs, *args, method=method, **kwargs)
  File "/Users/giuscarl/miniconda3/envs/netket_env/lib/python3.9/site-packages/flax/linen/module.py", line 862, in init_with_output
    return self.apply(
  File "/Users/giuscarl/miniconda3/envs/netket_env/lib/python3.9/site-packages/flax/linen/module.py", line 841, in apply
    return apply(fn, mutable=mutable)(variables, rngs=rngs)
  File "/Users/giuscarl/miniconda3/envs/netket_env/lib/python3.9/site-packages/flax/core/scope.py", line 608, in wrapper
    y = fn(root, *args, **kwargs)
  File "/Users/giuscarl/miniconda3/envs/netket_env/lib/python3.9/site-packages/flax/linen/module.py", line 834, in <lambda>
    fn = lambda scope: method(self.clone(parent=scope), *args, **kwargs)
  File "/Users/giuscarl/miniconda3/envs/netket_env/lib/python3.9/site-packages/flax/linen/module.py", line 277, in wrapped_module_method
    y = fun(self, *args, **kwargs)
  File "/Users/giuscarl/Works/NetKet/netket/netket/models/equivariant.py", line 137, in __call__
    x = self.equivariant_layers[layer](x)
  File "/Users/giuscarl/miniconda3/envs/netket_env/lib/python3.9/site-packages/flax/linen/module.py", line 277, in wrapped_module_method
    y = fun(self, *args, **kwargs)
  File "/Users/giuscarl/Works/NetKet/netket/netket/nn/linear.py", line 418, in __call__
    kernel = self.full_kernel(kernel)
  File "/Users/giuscarl/miniconda3/envs/netket_env/lib/python3.9/site-packages/flax/linen/module.py", line 277, in wrapped_module_method
    y = fun(self, *args, **kwargs)
  File "/Users/giuscarl/Works/NetKet/netket/netket/nn/linear.py", line 388, in full_kernel
    result = result.transpose(2, 0, 3, 1).reshape(
TypeError: transpose() takes from 1 to 2 positional arguments but 5 were given
```

not sure this is being addressed already in one of the open PRs about GCNNs and related? 

In any case, I think that this means that we do not have enough tests to cover GCNNs, since AFAIK all tests are passing @chrisrothUT

**Comment by chrisrothUT** [comment]
This bug is because transpose is supposed to take a tuple or list of indices so it should be result.transpose((0,2,3,1)). It looks like different setups handle this differently so I’m not sure how we could write a test for this particular issue.

I’ll fix the bug ASAP

**Comment by attila-i-szabo** [comment]
It might be worth a bug report to JAX too because they advertise that `result.transpose(2, 0, 3, 1)` should work

**Comment by gcarleo** [comment]
so you mean this is something that used to work in older versions of Jax? (I think we have a test on GCNN, I am just puzzled why the test passed... in principle we also have automatic testing for new versions of Jax, so they should have errored there)

**Comment by PhilipVinc** [comment]
It might be that this might be something they ‘banned’ on the latest release.

they try in general to enforce that shapes should be tuples. 
sometimes things slept past unnoticed and they remove them later claiming that it’s ok because they declare that they only want shapes as tuples.

**Comment by attila-i-szabo** [comment]
so much for just writing `jnp` instead of `np`... 
they should update the docs then, because it still says `ndarray.transpose(*axes)` on their website...

**Comment by PhilipVinc** [comment]
Every time I tried reporting this kind of things I’m told that it’s intended. So I pretty much stopped.

you can try. Maybe this is not intended.

However this means we are not testing it. We should add a test.

**Comment by gcarleo** [comment]
yes, all models should be tested at least in their call method

**Comment by attila-i-szabo** [comment]
> you can try. Maybe this is not intended.

I've seen how well arguing with the Jax people about design choice tends to go ;)

**Comment by gcarleo** [comment]
on the longer run we might want to add a bot that periodically runs full tests of the tutorials... that should be feasible I guess

**Comment by attila-i-szabo** [comment]
GCNN is tested here though:
https://github.com/netket/netket/blob/b8782770a5b1bb772c5ba6d4c0b607e814a51b50/Test/Models/test_rbm.py#L60
This should've errored out on this

**Comment by gcarleo** [comment]
uhmm weird, can you guys reproduce this issue locally? or is it only me?

**Comment by attila-i-szabo** [comment]
It works fine for me (at least when I switch to SGD, I can't keep track of what version of SR I have installed...) I use jax0.2.13 and jaxlib0.1.65

**Comment by gcarleo** [comment]
I see... found the culprit  
```
 print (jax.__version__)
0.2.10
```
with the latest version it's fine, mmmmm super random, I don't like this at all

**Comment by chrisrothUT** [comment]
Is this still worth changing? If so I can just change it in my next PR which should be in the near future.

**Comment by gcarleo** [comment]
I would still change it, since in principle we are also supporting that "old" version of jax...

**Comment by PhilipVinc** [comment]
The issue here is that tests run with the latest version of Jax that we declare compatible. 
So we are always sure that netket runs with the latest version of jax.

But we never run tests on the oldest supported version.
So new features might not be compatible.

We would need to run tests on the oldest, but it's not trivial to tell pip to install oldest compatible versions (or at least, I don't know how to do it).
