### ISSUE TITLE
(Excessively) out of memory in `expect_and_grad`

### ISSUE THREAD

**Issue by attila-i-szabo** [netket/netket#711]
I have tried to run a moderately sized model on a single GPU (no MPI). `Vmc::expect_and_grad` crashes when it attempts to allocate about 1TB of memory:
```
2021-05-15 17:06:18.153586: W external/org_tensorflow/tensorflow/compiler/xla/service/gpu/gpu_conv_algorithm_picker.cc:780] Failed to determine best cudnn convolution algorithm: Resource exhausted: Allocating 174487240704 bytes exceeds the memory limit of 4294967296 bytes.

Convolution performance may be suboptimal.
2021-05-15 17:06:18.159994: W external/org_tensorflow/tensorflow/compiler/xla/service/gpu/gpu_conv_algorithm_picker.cc:780] Failed to determine best cudnn convolution algorithm: Resource exhausted: Allocating 465299308544 bytes exceeds the memory limit of 4294967296 bytes.

Convolution performance may be suboptimal.
2021-05-15 17:06:18.161074: W external/org_tensorflow/tensorflow/compiler/xla/service/gpu/gpu_conv_algorithm_picker.cc:780] Failed to determine best cudnn convolution algorithm: Resource exhausted: Allocating 465299308544 bytes exceeds the memory limit of 4294967296 bytes.

Convolution performance may be suboptimal.
2021-05-15 17:06:33.088411: W external/org_tensorflow/tensorflow/core/common_runtime/bfc_allocator.cc:457] Allocator (GPU_0_bfc) ran out of memory trying to allocate 977.79GiB (rounded to 1049890968832)requested by op 
2021-05-15 17:06:33.088942: W external/org_tensorflow/tensorflow/core/common_runtime/bfc_allocator.cc:468] *****_______________________________________________________________________________________________
2021-05-15 17:06:33.089058: E external/org_tensorflow/tensorflow/compiler/xla/pjrt/pjrt_stream_executor_client.cc:1981] Execution of replica 0 failed: Resource exhausted: Out of memory while trying to allocate 1049890968768 bytes.
Traceback (most recent call last):
  File "/home/vol06/scarf1036/NQS/python/expt1.py", line 88, in <module>
    vmc.run(n_iter=1000, out=f"{output_dir}/expt1")
  File "/home/vol06/scarf1036/.venv/netket/lib/python3.8/site-packages/netket/driver/abstract_variational_driver.py", line 252, in run
    for step in itr:
  File "/home/vol06/scarf1036/.venv/netket/lib/python3.8/site-packages/tqdm/std.py", line 1178, in __iter__
    for obj in iterable:
  File "/home/vol06/scarf1036/.venv/netket/lib/python3.8/site-packages/netket/driver/abstract_variational_driver.py", line 167, in iter
    dp = self._forward_and_backward()
  File "/home/vol06/scarf1036/.venv/netket/lib/python3.8/site-packages/netket/driver/vmc.py", line 115, in _forward_and_backward
    self._loss_stats, self._loss_grad = self.state.expect_and_grad(self._ham)
  File "/home/vol06/scarf1036/.venv/netket/lib/python3.8/site-packages/netket/variational/mc_state.py", line 469, in expect_and_grad
    Ō, Ō_grad, new_model_state = grad_expect_hermitian(
  File "/home/vol06/scarf1036/.venv/netket/lib/python3.8/site-packages/jax/_src/traceback_util.py", line 143, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
File "/home/vol06/scarf1036/.venv/netket/lib/python3.8/site-packages/jax/_src/api.py", line 426, in cache_miss
    out_flat = xla.xla_call(
  File "/home/vol06/scarf1036/.venv/netket/lib/python3.8/site-packages/jax/core.py", line 1565, in bind
    return call_bind(self, fun, *args, **params)
  File "/home/vol06/scarf1036/.venv/netket/lib/python3.8/site-packages/jax/core.py", line 1556, in call_bind
    outs = primitive.process(top_trace, fun, tracers, params)
  File "/home/vol06/scarf1036/.venv/netket/lib/python3.8/site-packages/jax/core.py", line 1568, in process
    return trace.process_call(self, fun, tracers, params)
  File "/home/vol06/scarf1036/.venv/netket/lib/python3.8/site-packages/jax/core.py", line 609, in process_call
    return primitive.impl(f, *tracers, **params)
  File "/home/vol06/scarf1036/.venv/netket/lib/python3.8/site-packages/jax/interpreters/xla.py", line 581, in _xla_call_impl
    return compiled_fun(*args)
  File "/home/vol06/scarf1036/.venv/netket/lib/python3.8/site-packages/jax/interpreters/xla.py", line 874, in _execute_compiled
    out_bufs = compiled.execute(input_bufs)
jax._src.traceback_util.UnfilteredStackTrace: RuntimeError: Resource exhausted: Out of memory while trying to allocate 1049890968768 bytes.
```
It seems that the demand for all this memory comes from `mc_state::grad_expect_hermitian`, which only contains a single VJP. I checked that with the settings I was using (1024 samples on a 10x10 lattice), a VJP only requires 1.5 GB of memory, rather than the ~1TB that is attempted to be allocated. I cannot imagine what would require this much memory... 
If that's helpful for debugging, the code uses LAX-based convolutional layers and it's written in STAX. ~I have run the same code on CPUs also, and never had such a problem.~

**Comment by attila-i-szabo** [comment]
On further inspection, it seems that the OOM comes from calculating the expectation values. However, even calculating 1024×200 wave function entries (200 is an upper bound for σ' states for each σ) requires much less memory, so I still don't understand what would try to allocate 1TB...

**Comment by PhilipVinc** [comment]
Hard to say without seeing the network you are trying to work with.
Do you have a limited reproducer of the issue?

>On further inspection, it seems that the OOM comes from calculating the expectation values. 

Do you mean you get OOM also from calling just `expect()`?

You can also try to run it under jax profiler. I think you should, with a lot of work, eventually understand where the allocations come from.

**Comment by guglami** [comment]
I also have a similar problem! I'm using a custom model, written in the Flax framework. 
With moderately sized systems and number of samples, I get: 
  File "/home/glami/.local/lib/python3.8/site-packages/netket/variational/mc_state.py", line 404, in expect
    return _expect(
jax._src.traceback_util.FilteredStackTrace: RuntimeError: Resource exhausted: Failed to allocate request for 55.97GiB (60096009848B) on device ordinal 0 
I'm running with mpirun, cpus_per_tasks=2, n_nodes=4, no gpus. How to de-bug?

**Comment by gcarleo** [comment]
is it possible that Jax is allocating memory for backpropagation even if we are not doing any backprop? 

I think it would be very important for us to understand where the issue is in these cases, and see if we are causing some unnecessary memory allocation or if it's not our fault!

**Comment by gcarleo** [comment]
is it possible that Jax is allocating memory for backpropagation even if we are not doing any backprop? 

I think it would be very important for us to understand where the issue is in these cases, and see if we are causing some unnecessary memory allocation or if it's not our fault!

**Comment by PhilipVinc** [comment]
>is it possible that Jax is allocating memory for backpropagation even if we are not doing any backprop?

I would exclude it: The way Jax works is that essentially it builds the computational graph and then executes it.
If you never execute grad or vjp, he does not have those things in the network.

I think that [reading the Jax docs about memory profiling](https://jax.readthedocs.io/en/latest/device_memory_profiling.html) might have been written exactly for this kind of problem.

I don't know if it's relevant, but maybe commenting `netket/stats/mc_stats:175-250` might help?

**Comment by PhilipVinc** [comment]
That is the only _weird_ code that I don't know what might be its performance and is executed in `expect`. 
Everything else is really just evaluating your model in a single huge batch.
Without an example code it's impossible to say anything more.

**Comment by chrisrothUT** [comment]
I’ve also been running into memory errors for a moderately sized model with batch size 1000 on the sr-rework branch. 

The errors didn’t appear on the older version “sr-types” and they don’t appear on “master”, so I think this might be a newly introduced bug on the sr-rework branch.

**Comment by gcarleo** [comment]
@chrisrothUT did you solve your issue of memory? (your comment disappeared)

**Comment by chrisrothUT** [comment]
Sorry, I deleted because I wasn’t sure if a) it was a bug or related to the GPU I was allocated b) The memory issues occurred during solve (with precomputed grads). 

I’ll do more investigating and post if I’m sure it’s not on my end.

**Comment by PhilipVinc** [comment]
>The memory issues occurred during solve (with precomputed grads).

Precomputed grads where not there before. Before the only thing you could use was OnTheFly and that did not change.

**Comment by attila-i-szabo** [comment]
It turns out that I underestimated how much memory is required to evaluate my model for all spin configurations in `expect` -- I can account for about 400 GiB, the rest probably comes from minor inefficiencies in coding and `jit`. 

Nevertheless, it would be nice to redesign functions with potentially huge memory demands to allow breaking big `vmap`s up. `expect` is a good example because one can easily need hundreds of thousands of neural network outputs, so only very lean models would fit on one GPU in one iteration...
