### ISSUE TITLE
[BUG] QGTJacobian*** with R->C model and C gradient does not work.

### ISSUE THREAD

**Issue by PhilipVinc** [netket/netket#789]
As title.
I think SR (as in natural gradient) should still be well defined in that case.
OnTheFly works correctly

cc @inailuig @attila-i-szabo 

```python
import netket as nk
import jax

# 1D Lattice
L = 20  # 10

g = nk.graph.Hypercube(length=L, n_dim=1, pbc=True)

# Hilbert space of spins on the graph
hi = nk.hilbert.Spin(s=1 / 2, N=g.n_nodes)

# Ising spin hamiltonian
ha = nk.operator.Ising(hilbert=hi, graph=g, h=1.0)

# RBM Spin Machine
ma = nk.models.RBMModPhase(alpha=1, dtype=float)

# Metropolis Local Sampling
sa = nk.sampler.MetropolisLocal(hi, n_chains=16, reset_chains=False)

vs = nk.variational.MCState(sa, ma, n_samples=1000, n_discard_per_chain=100)

S = vs.quantum_geometric_tensor(nk.optimizer.qgt.QGTJacobianPyTree)

g_cmplx = jax.tree_map(lambda x: x + x*0.1j, vs.parameters)

S@g_cmplx
```

```python
>>> S@g_cmplx
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/filippovicentini/Dropbox/Ricerca/Codes/Python/netket/netket/optimizer/qgt/qgt_jacobian_pytree.py", line 137, in __matmul__
    return _matmul(self, vec)
  File "/home/filippovicentini/Documents/pythonenvs/netket_env/lib64/python3.8/site-packages/jax/_src/traceback_util.py", line 183, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/home/filippovicentini/Documents/pythonenvs/netket_env/lib64/python3.8/site-packages/jax/_src/api.py", line 424, in cache_miss
    out_flat = xla.xla_call(
  File "/home/filippovicentini/Documents/pythonenvs/netket_env/lib64/python3.8/site-packages/jax/core.py", line 1560, in bind
    return call_bind(self, fun, *args, **params)
  File "/home/filippovicentini/Documents/pythonenvs/netket_env/lib64/python3.8/site-packages/jax/core.py", line 1551, in call_bind
    outs = primitive.process(top_trace, fun, tracers, params)
  File "/home/filippovicentini/Documents/pythonenvs/netket_env/lib64/python3.8/site-packages/jax/core.py", line 1563, in process
    return trace.process_call(self, fun, tracers, params)
  File "/home/filippovicentini/Documents/pythonenvs/netket_env/lib64/python3.8/site-packages/jax/core.py", line 606, in process_call
    return primitive.impl(f, *tracers, **params)
  File "/home/filippovicentini/Documents/pythonenvs/netket_env/lib64/python3.8/site-packages/jax/interpreters/xla.py", line 592, in _xla_call_impl
    compiled_fun = _xla_callable(fun, device, backend, name, donated_invars,
  File "/home/filippovicentini/Documents/pythonenvs/netket_env/lib64/python3.8/site-packages/jax/linear_util.py", line 262, in memoized_fun
    ans = call(fun, *args)
  File "/home/filippovicentini/Documents/pythonenvs/netket_env/lib64/python3.8/site-packages/jax/interpreters/xla.py", line 667, in _xla_callable
    jaxpr, out_avals, consts = pe.trace_to_jaxpr_final(
  File "/home/filippovicentini/Documents/pythonenvs/netket_env/lib64/python3.8/site-packages/jax/interpreters/partial_eval.py", line 1284, in trace_to_jaxpr_final
    jaxpr, out_avals, consts = trace_to_subjaxpr_dynamic(fun, main, in_avals)
  File "/home/filippovicentini/Documents/pythonenvs/netket_env/lib64/python3.8/site-packages/jax/interpreters/partial_eval.py", line 1262, in trace_to_subjaxpr_dynamic
    ans = fun.call_wrapped(*in_tracers)
  File "/home/filippovicentini/Documents/pythonenvs/netket_env/lib64/python3.8/site-packages/jax/linear_util.py", line 166, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "/home/filippovicentini/Dropbox/Ricerca/Codes/Python/netket/netket/optimizer/qgt/qgt_jacobian_pytree.py", line 185, in _matmul
    result = mat_vec(vec, self.O, self.diag_shift)
  File "/home/filippovicentini/Dropbox/Ricerca/Codes/Python/netket/netket/optimizer/qgt/qgt_jacobian_pytree_logic.py", line 285, in mat_vec
    return tree_axpy(diag_shift, v, _mat_vec(v, centered_oks))
  File "/home/filippovicentini/Dropbox/Ricerca/Codes/Python/netket/netket/optimizer/qgt/qgt_jacobian_pytree_logic.py", line 173, in _mat_vec
    res = tree_conj(_vjp(oks, _jvp(oks, v).conjugate()))
  File "/home/filippovicentini/Dropbox/Ricerca/Codes/Python/netket/netket/optimizer/qgt/qgt_jacobian_pytree_logic.py", line 158, in _jvp
    return jax.tree_util.tree_reduce(jnp.add, jax.tree_multimap(td, oks, v))
  File "/home/filippovicentini/Documents/pythonenvs/netket_env/lib64/python3.8/site-packages/jax/_src/tree_util.py", line 168, in tree_map
    return treedef.unflatten(f(*xs) for xs in zip(*all_leaves))
  File "/home/filippovicentini/Documents/pythonenvs/netket_env/lib64/python3.8/site-packages/jax/_src/tree_util.py", line 168, in <genexpr>
    return treedef.unflatten(f(*xs) for xs in zip(*all_leaves))
  File "/home/filippovicentini/Dropbox/Ricerca/Codes/Python/netket/netket/optimizer/qgt/qgt_jacobian_pytree_logic.py", line 157, in <lambda>
    td = lambda x, y: jnp.tensordot(x, y, axes=y.ndim)
jax._src.traceback_util.UnfilteredStackTrace: AttributeError: 'tuple' object has no attribute 'ndim'

The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.

--------------------

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/filippovicentini/Dropbox/Ricerca/Codes/Python/netket/netket/optimizer/qgt/qgt_jacobian_pytree.py", line 137, in __matmul__
    return _matmul(self, vec)
  File "/home/filippovicentini/Dropbox/Ricerca/Codes/Python/netket/netket/optimizer/qgt/qgt_jacobian_pytree.py", line 185, in _matmul
    result = mat_vec(vec, self.O, self.diag_shift)
  File "/home/filippovicentini/Dropbox/Ricerca/Codes/Python/netket/netket/optimizer/qgt/qgt_jacobian_pytree_logic.py", line 285, in mat_vec
    return tree_axpy(diag_shift, v, _mat_vec(v, centered_oks))
  File "/home/filippovicentini/Dropbox/Ricerca/Codes/Python/netket/netket/optimizer/qgt/qgt_jacobian_pytree_logic.py", line 173, in _mat_vec
    res = tree_conj(_vjp(oks, _jvp(oks, v).conjugate()))
  File "/home/filippovicentini/Dropbox/Ricerca/Codes/Python/netket/netket/optimizer/qgt/qgt_jacobian_pytree_logic.py", line 158, in _jvp
    return jax.tree_util.tree_reduce(jnp.add, jax.tree_multimap(td, oks, v))
  File "/home/filippovicentini/Dropbox/Ricerca/Codes/Python/netket/netket/optimizer/qgt/qgt_jacobian_pytree_logic.py", line 157, in <lambda>
    td = lambda x, y: jnp.tensordot(x, y, axes=y.ndim)
AttributeError: 'tuple' object has no attribute 'ndim'
```

**Comment by attila-i-szabo** [comment]
> I think SR (as in natural gradient) should still be well defined in that case.

Well, it's not a case you'd encounter in VMC, the RHS of the SR equation is real if the corresponding parameter is real.

But this bug is weirder. It looks like the pytree structures of the Jacobian and `g_cmplx` don't match. The latter must be the same (modulo dtype but that shouldn't cause this error) as `vs.parameters` unless there's a weird bug here:
```python
g_cmplx = jax.tree_map(lambda x: x + x*0.1j, vs.parameters)
```
Does it work if you supply `vs.parameters` as the RHS?

**Comment by PhilipVinc** [comment]
yes it does. I think it's because you are not 'splitting' the variables into tuples of real and imaginary part (because they are real) but you are splitting the vector, so the tree shapes dont match anymore.

**Comment by attila-i-szabo** [comment]
> I think it's because you are not 'splitting' the variables into tuples of real and imaginary part (because they are real) but you are splitting the vector.
> vs.parameters is real, so it does not get split, but the complexified version i create is split so the tree shapes dont match anymore.

Good catch! The splitting is needed though for complex parameters where the Jacobian is split too. You could make a version of `tree_to_real` or whatever it was called which changes behaviour (split or not split) based on the structure of a reference pytree to fix that.

> Yeah ok. But I am starting to feel bored with VMC and wanted to try something new blush.

Sounds exciting :)

**Comment by PhilipVinc** [comment]
So in theory if i don't split the vector in this case, everything should be fine, right?

I'll try to fix this and add a whole lot of tests

**Comment by attila-i-szabo** [comment]
Yup. The best might be replacing `tree_to_real` with something along the following lines:
```python
def split_if_cplx(tree, ref):
    return tree_multimap(lambda x,y: (y.real, y.imag) if iscomplexobj(x) else y, ref, tree)
```
`ref` would be the unsplit tree of parameters, so leaves of `tree` would be split iff the corresponding one in `ref` is complex

**Comment by inailuig** [comment]
OnTheFly only "works" because it casts away the complex part of g_cmplx
in https://github.com/netket/netket/blob/cd70d32bc4d149cbb22d5331e0f4dec4606b0431/netket/optimizer/qgt/qgt_onthefly.py#L142
so I guess it doesn't actually do what @PhilipVinc wants.

I think the only simple way to do this is to pass the re and im parts as two separate real vectors.
I'll open a PR soon for getting rid of the real-imag split. Then, for JacobianPytree, ideally with a zero-copy bitcast (https://github.com/netket/netket/pull/674/files#r633665248) and by using some of https://github.com/inailuig/pytreearray (the library suggested in https://github.com/netket/netket/pull/674#issuecomment-841625703; mostly the transpositions + some maybe other goodies) it should be possible to do this efficiently by casting the complex vector to a real n x 2 matrix.

**Comment by gcarleo** [comment]
> https://github.com/inailuig/pytreearray (the library suggested in #674 (comment); 
Oh nice @inailuig , I think that is very useful !

**Comment by PhilipVinc** [comment]
This is now solved by throwing a relevant error
```

RealQGTComplexDomainError:
            Cannot multiply the (real part of the) QGT by a complex vector.
            You should either take the real part of the vector, or perform
            the multiplication against the real and imaginary part of the
            vector separately and then recomposing the two.

            This is happening because you have real parameters or a non-holomorphic
            complex wave function. In this case, the Quantum Geometric Tensor object
            only stores the real part of the QGT.

            If you were executing a matmul `G@vec`, try using:

            .. code:: python

               >>> vec_real = jax.tree_map(lambda x: x.real, vec)
               >>> G@vec_real

            If you used the QGT in a linear solver, try using:

            .. code:: python

               >>> vec_real = jax.tree_map(lambda x: x.real, vec)
               >>> G.solve(linear_solver, vec_real)

            to fix this error.

            Be careful whether you need the real or imaginary part
            of the vector in your equations!
```
