### ISSUE TITLE
Can't use optimiser schedules

### ISSUE THREAD

**Issue by attila-i-szabo** [netket/netket#908]
Optax supports learning rate schedules, i.e., `optax.sgd` and all the others are able to take an integer→float function that tells what learning rate to use at the nth step.

This functionality doesn't work in NetKet. Say, I want to define SGD with restarts as follows:
```python
def schedule(n):
    restart=100
    return (1+np.cos(pi*(n%restart)/restart)) * η
op = nk.optimizer.Sgd(schedule)
```
When I try to run VMC with this optimiser, I get the error message at the bottom. It complains about the jitting of the update function here: https://github.com/netket/netket/blob/284ef070e6926f69b113b072ae52d08e6a9c7003/netket/driver/abstract_variational_driver.py#L317
Indeed, after removing this jit everything runs fine. However, it is weird that it causes a problem, it would make sense to jit over only the parts where you already have the learning rate...

Is the jit really necessary here? Or is this something better treated by changing optax?

```
Traceback (most recent call last):
  File "../run.py", line 114, in <module>
    gs.run(n_iter=1000, out=filename(2))
  File "/mnt/beegfs/home/pearl068/.venv/netket/lib/python3.7/site-packages/netket/driver/abstract_variational_driver.py", line 251, in run
    for step in self.iter(n_iter, step_size):
  File "/mnt/beegfs/home/pearl068/.venv/netket/lib/python3.7/site-packages/netket/driver/abstract_variational_driver.py", line 172, in iter
    self.update_parameters(dp)
  File "/mnt/beegfs/home/pearl068/.venv/netket/lib/python3.7/site-packages/netket/driver/abstract_variational_driver.py", line 313, in update_parameters
    self._optimizer.update, self._optimizer_state, dp, self.state.parameters
  File "/mnt/beegfs/home/pearl068/.venv/netket/lib/python3.7/site-packages/jax/_src/traceback_util.py", line 162, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/mnt/beegfs/home/pearl068/.venv/netket/lib/python3.7/site-packages/jax/_src/api.py", line 408, in cache_miss
    donated_invars=donated_invars, inline=inline)
  File "/mnt/beegfs/home/pearl068/.venv/netket/lib/python3.7/site-packages/jax/core.py", line 1614, in bind
    return call_bind(self, fun, *args, **params)
  File "/mnt/beegfs/home/pearl068/.venv/netket/lib/python3.7/site-packages/jax/core.py", line 1605, in call_bind
    outs = primitive.process(top_trace, fun, tracers, params)
  File "/mnt/beegfs/home/pearl068/.venv/netket/lib/python3.7/site-packages/jax/core.py", line 1617, in process
    return trace.process_call(self, fun, tracers, params)
  File "/mnt/beegfs/home/pearl068/.venv/netket/lib/python3.7/site-packages/jax/core.py", line 613, in process_call
    return primitive.impl(f, *tracers, **params)
  File "/mnt/beegfs/home/pearl068/.venv/netket/lib/python3.7/site-packages/jax/interpreters/xla.py", line 620, in _xla_call_impl
    *unsafe_map(arg_spec, args))
  File "/mnt/beegfs/home/pearl068/.venv/netket/lib/python3.7/site-packages/jax/linear_util.py", line 262, in memoized_fun
    ans = call(fun, *args)
  File "/mnt/beegfs/home/pearl068/.venv/netket/lib/python3.7/site-packages/jax/interpreters/xla.py", line 697, in _xla_callable
    fun, abstract_args, pe.debug_info_final(fun, "jit"))
  File "/mnt/beegfs/home/pearl068/.venv/netket/lib/python3.7/site-packages/jax/interpreters/partial_eval.py", line 1285, in trace_to_jaxpr_final
    jaxpr, out_avals, consts = trace_to_subjaxpr_dynamic(fun, main, in_avals)
  File "/mnt/beegfs/home/pearl068/.venv/netket/lib/python3.7/site-packages/jax/interpreters/partial_eval.py", line 1263, in trace_to_subjaxpr_dynamic
    ans = fun.call_wrapped(*in_tracers)
  File "/mnt/beegfs/home/pearl068/.venv/netket/lib/python3.7/site-packages/jax/linear_util.py", line 166, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "/mnt/beegfs/home/pearl068/.venv/netket/lib/python3.7/site-packages/netket/driver/abstract_variational_driver.py", line 321, in apply_gradient
    updates, new_optimizer_state = optimizer_fun(dp, optimizer_state, params)
  File "/mnt/beegfs/home/pearl068/.venv/netket/lib/python3.7/site-packages/optax/_src/transform.py", line 605, in update_fn
    step_size = step_size_fn(state.count)
  File "../pyrochlore.py", line 106, in schedule
    return (1+np.cos(pi*(n%restart)/restart))*η
  File "/mnt/beegfs/home/pearl068/.venv/netket/lib/python3.7/site-packages/jax/core.py", line 476, in __array__
    raise TracerArrayConversionError(self)
jax._src.traceback_util.UnfilteredStackTrace: jax._src.errors.TracerArrayConversionError: The numpy.ndarray conversion method __array__() was called on the JAX Tracer object Traced<ShapedArray(float64[], weak_type=True)>with<DynamicJaxprTrace(level=0/1)>
While tracing the function apply_gradient at /mnt/beegfs/home/pearl068/.venv/netket/lib/python3.7/site-packages/netket/driver/abstract_variational_driver.py:317 for jit, this concrete value was not available in Python because it depends on the value of the argument passed at flattened position 0.
See https://jax.readthedocs.io/en/latest/errors.html#jax.errors.TracerArrayConversionError

The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.

--------------------

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "../run.py", line 114, in <module>
    gs.run(n_iter=1000, out=filename(2))
  File "/mnt/beegfs/home/pearl068/.venv/netket/lib/python3.7/site-packages/netket/driver/abstract_variational_driver.py", line 251, in run
    for step in self.iter(n_iter, step_size):
  File "/mnt/beegfs/home/pearl068/.venv/netket/lib/python3.7/site-packages/netket/driver/abstract_variational_driver.py", line 172, in iter
    self.update_parameters(dp)
  File "/mnt/beegfs/home/pearl068/.venv/netket/lib/python3.7/site-packages/netket/driver/abstract_variational_driver.py", line 313, in update_parameters
    self._optimizer.update, self._optimizer_state, dp, self.state.parameters
  File "/mnt/beegfs/home/pearl068/.venv/netket/lib/python3.7/site-packages/netket/driver/abstract_variational_driver.py", line 321, in apply_gradient
    updates, new_optimizer_state = optimizer_fun(dp, optimizer_state, params)
  File "/mnt/beegfs/home/pearl068/.venv/netket/lib/python3.7/site-packages/optax/_src/transform.py", line 605, in update_fn
    step_size = step_size_fn(state.count)
  File "../pyrochlore.py", line 106, in schedule
    return (1+np.cos(pi*(n%restart)/restart))*η
jax._src.errors.TracerArrayConversionError: The numpy.ndarray conversion method __array__() was called on the JAX Tracer object Traced<ShapedArray(float64[], weak_type=True)>with<DynamicJaxprTrace(level=0/1)>
While tracing the function apply_gradient at /mnt/beegfs/home/pearl068/.venv/netket/lib/python3.7/site-packages/netket/driver/abstract_variational_driver.py:317 for jit, this concrete value was not available in Python because it depends on the value of the argument passed at flattened position 0.
See https://jax.readthedocs.io/en/latest/errors.html#jax.errors.TracerArrayConversionError
```

**Comment by gcarleo** [comment]
yes the solution is to use directly the optax optimizer, see this [tutorial](https://github.com/CRC183-summer-school/school_2021/blob/main/notebooks/02_netket.ipynb) I gave around In[29]

**Comment by PhilipVinc** [comment]
According to optax documentation an arbitrary function is not supported, only a schedule (which allows for the same generality, only, I guess, Is registered as a pyTree).

anyhow, your approach is probably fine, you just have to make the schedule a pyTree. By making it a nk.utils.struct.dataclass for example.

The jit is almost useless for sgd on tiny models, but if you have a lot of weight tensors and a more complex optimiser it does show a small speedup 


maybe if you use a

**Comment by attila-i-szabo** [comment]
> use directly the optax optimizer

Replacing `op = nk.optimizer.Sgd(schedule)` with `op = optax.sgd(schedule)` in my example leads to the same outcome (it should as `Sgd` is just a thin wrapper around `sgd`)

> According to optax documentation an arbitrary function is not supported, only a schedule (which allows for the same generality, only, I guess, Is registered as a pyTree).

What I don't get is that the schedules are implemented in optax to return functions, not some sort of pytree objects

> anyhow, your approach is probably fine, you just have to make the schedule a pyTree. By making it a nk.utils.struct.dataclass for example.

Would that go like this?
```python
@dataclass
class schedule:
  def __call__(n):
    return ...
```

**Comment by PhilipVinc** [comment]
> Replacing op = nk.optimizer.Sgd(schedule) with op = optax.sgd(schedule) in my example leads to the same outcome (it should as Sgd is just a thin wrapper around sgd)

I think Giuseppe meant don’t use your schedule, use optax. 
check the tutorial that is on netket’s website, at the end, there’s an example.

> What I don't get is that the schedules are implemented in optax to return functions, not some sort of pytree objects, see here

there’s logic to it.
Just read the design docs over at optax. They documented their choice decently.

> Would that go like this?

I don’t know. You must use a pyTree dataclass, so either netket’s or flax’s.

— 

anyhow, i just noticed that the culprit is another one.
If you pay attention to t error message you’ll see it’s a concrétisation error.
You’re using np instead of jnp, probably.

**Comment by PhilipVinc** [comment]
np.cos

**Comment by attila-i-szabo** [comment]
> np.cos

Indeed, thanks for spotting that. For the record,
```python3
def schedule(n):
    restart=100
    return (1+jnp.cos(pi*(n%restart)/restart)) * η
op = optax.sgd(schedule)
```
works. Apparently all that is needed is a schedule function that can be jitted itself, a pytree isn't necessary (but it might be good to hide `if` statements or something?)

> Just read the design docs over at optax. They documented their choice decently.

Where are these actually?

**Comment by PhilipVinc** [comment]
>Where are these actually?

I cannot find anymore the issue where they were discussing the design of schedules, but I'm sure it's somewhere. I also read several times through [FLIP#1009](https://github.com/google/flax/blob/main/docs/flip/1009-optimizer-api.md) that gives an overview, or https://github.com/deepmind/optax/issues/20 and others when I was considering what framework to use.

Anyhow, optax schedules return a function because you want to pass to the optimizer a function (or a number). Since you are giving it the function directly then it's as if you already built it.

Essentially, either you return a function or return a Partial. They chose to return a function.

**Comment by PhilipVinc** [comment]
I'll close this because it's not an issue with netket or optax.
