### ISSUE TITLE
Problems with optax.masked

### ISSUE THREAD

**Issue by SemyonSinchenko** [netket/netket#916]
Hello!

I want to use `optax.masked` to try something like "transfer learning" in NQS: I want to use a part of pre-trained weights from another model and another random-initialized part of weights. And I want to "freeze" a pre-trained base of the model and train only a head of the model. But when I pass `optax.masked` to the VMC I got an error:

```{python}
Traceback (most recent call last):
  File "trf_main.py", line 64, in <module>
    model.set_vmc()
  File "/home/sem/GitHub/XXModelNQS/project/src/model/tl_experiment.py", line 80, in set_vmc
    preconditioner=nk.optimizer.SR(),
  File "/home/sem/GitHub/XXModelNQS/.venv/lib/python3.7/site-packages/netket/driver/vmc.py", line 111, in __init__
    super().__init__(variational_state, optimizer, minimized_quantity_name="Energy")
  File "/home/sem/GitHub/XXModelNQS/.venv/lib/python3.7/site-packages/netket/driver/abstract_variational_driver.py", line 67, in __init__
    self.optimizer = optimizer
  File "/home/sem/GitHub/XXModelNQS/.venv/lib/python3.7/site-packages/netket/driver/abstract_variational_driver.py", line 142, in optimizer
    self._optimizer_state = optimizer.init(self.state.parameters)
  File "/home/sem/GitHub/XXModelNQS/.venv/lib/python3.7/site-packages/optax/_src/wrappers.py", line 311, in init_fn
    flat_params = treedef.flatten_up_to(params)
ValueError: Expected dict, got FrozenDict({....

```

I found an issue in optax repository: [optax.mask does not play well with flax FrozenParams](https://github.com/deepmind/optax/issues/160) and the solution is to use `flax.core.unfreeze`. But I cannot use `unfreeze` because even if I pass to `MCState` construtctor unfrozen dict it will be frozen in `netket.vqs.base.py` (if I understood this code right):
```{python}
    @parameters.setter
    def parameters(self, pars: PyTree):
        if not isinstance(pars, FrozenDict):
            if not isinstance(pars, list) and not isinstance(pars, tuple):
                pars = flax.core.freeze(pars)

        self._parameters = pars
        self.reset()
```

How could I pass to the `optax.masked` an unfrozen regular dict with parameters instead of the `FrozenDict`? Or maybe there is another option how to use `optax.masked` in NetKet?
Thank you!

**Comment by PhilipVinc** [comment]
Yes the frozendict stuff is indeed confusing. Hopefully it will be eventually solved by flax people once they stop returning frzenDicts.

min the meantime, can you post the full example of what is triggering the error?

**Comment by PhilipVinc** [comment]
Also, see cell 47 of https://www.netket.org/tutorials/netket3.html . If you freeze the duct does it work?
Il 8 set 2021, 19:20 +0200, Semyon ***@***.***>, ha scritto:

**Comment by SemyonSinchenko** [comment]
> can you post the full example of what is triggering the error?

It is little hard because I have a lot of logic on top of the NetKet code. But I create a minimal reproducable example:
```{python}

import netket as nk
import optax
from flax.core import freeze, unfreeze
from jax import numpy as jnp
from jax.random import PRNGKey
from netket import nn


class MyNN(nn.Module):
    def setup(self):
        self.base = nn.Dense(
            features=20,
            dtype=jnp.complex64,
            use_bias=True,
            kernel_init=nn.initializers.normal(1e-1),
            bias_init=nn.initializers.normal(1e-4),
        )
        self.head = nn.Dense(
            features=5,
            dtype=jnp.complex64,
            use_bias=True,
            kernel_init=nn.initializers.normal(1e-1),
            bias_init=nn.initializers.normal(1e-4),
        )

    @nn.compact
    def __call__(self, x):
        x = self.base(x)
        x = self.head(x)
        x = nn.log_cosh(x)
        x = jnp.sum(x, axis=-1)

        return x


if __name__ == "__main__":
    graph = nk.graph.Chain(10)
    hi = nk.hilbert.Spin(s=0.5, N=10)
    op = nk.operator.Ising(hi, graph, 0.45, 1.0)
    model = MyNN()

    variables = model.init(PRNGKey(0), jnp.ones(10))
    variables = unfreeze(variables)

    # Here I want to use pre-trained `base`-weights from another model
    variables["params"]["base"]["kernel"] = jnp.ones((10, 50), dtype=jnp.complex64)

    mcstate = nk.vqs.MCState(
        sampler=nk.sampler.MetropolisLocal(hi),
        model=model,
        n_samples=500,
        variables=variables,
    )

    vmc = nk.driver.VMC(
        hamiltonian=op,
        optimizer=optax.masked(
            optax.sgd(learning_rate=0.1), {"base": False, "head": True}
        ),
        variational_state=mcstate,
        preconditioner=nk.optimizer.SR(solver_restart=False),
    )

    logger = nk.logging.RuntimeLog()
    vmc.run(
        n_iter=200,
        out=logger,
    )
```

And the error:
```{python}
WARNING:absl:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
Traceback (most recent call last):
  File "reproducable_example.py", line 61, in <module>
    preconditioner=nk.optimizer.SR(solver_restart=False),
  File "/home/sem/GitHub/XXModelNQS/.venv/lib/python3.7/site-packages/netket/driver/vmc.py", line 111, in __init__
    super().__init__(variational_state, optimizer, minimized_quantity_name="Energy")
  File "/home/sem/GitHub/XXModelNQS/.venv/lib/python3.7/site-packages/netket/driver/abstract_variational_driver.py", line 67, in __init__
    self.optimizer = optimizer
  File "/home/sem/GitHub/XXModelNQS/.venv/lib/python3.7/site-packages/netket/driver/abstract_variational_driver.py", line 142, in optimizer
    self._optimizer_state = optimizer.init(self.state.parameters)
  File "/home/sem/GitHub/XXModelNQS/.venv/lib/python3.7/site-packages/optax/_src/wrappers.py", line 311, in init_fn
    flat_params = treedef.flatten_up_to(params)
ValueError: Expected dict, got FrozenDict({
    base: {
        bias: DeviceArray([ 7.49323444e-05-5.9041035e-05j,
                     -4.48851897e-05-5.0155333e-05j,
                     -4.31595327e-05+5.2189174e-05j,
                    ........
```

As you can see I pass to the MCState the unfrozen dict! And seems to me that the problem is here:
https://github.com/netket/netket/blob/master/netket/vqs/base.py#L81

What is the reason to freeze params in any case? Because next we pass to the optax `mcstate.params` here:
```
File "/home/sem/GitHub/XXModelNQS/.venv/lib/python3.7/site-packages/netket/driver/abstract_variational_driver.py", line 142, in optimizer
    self._optimizer_state = optimizer.init(self.state.parameters)
```

**Comment by PhilipVinc** [comment]
Try to change the definition of the optax optimizer to 

```python
optax.masked(
            optax.sgd(learning_rate=0.1), flax.core.freeze({"base": False, "head": True})
        )
```

**Comment by SemyonSinchenko** [comment]
@PhilipVinc WOW! Now it is working! Thanks a lot!!!

**Comment by PhilipVinc** [comment]
> What is the reason to freeze params in any case? Because next we pass to the optax mcstate.params here:

For posterity: the reason is that when i implemented this code Flax modules required parameters to be passed in as `FroxenDict`s, and they only recently relaxed this requirement. 

For that reason i implemented this code that ensures that parameters are always froxen.

We might remove this code now, but it would be a breaking change because it requires users to update their usage of `optax.masked` (essentially, they would have to remove the freeze call).

So it's a sensible thung to do but maybe it's best we wait a bit before doing it...
